name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  footer: ^0.0.4

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.12.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fordiseases/
